version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=smartgrow
      - POSTGRES_USER=smartgrow
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=smartgrow@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80
  # app:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   ports:
  #       - "3000:3000"
  #   volumes:
  #       - .:/app
