
version: "1.17.1"
services:

   
         
   influxdb:
      user: root
      image: "influxdb:latest"
      RESTART: unless-stopped
      ports:
         - "8086:8086"
      volumes:
         - ./data/influxdb/data:/var/lib/influxdb2
         - ./data/influxdb/config/:/etc/influxdb2
      environment:
         - DOCKER_INFLUXDB_INIT_MODE=setup
         - DOCKER_INFLUXDB_INIT_USERNAME=smartgrow
         - 'DOCKER_INFLUXDB_INIT_PASSWORD=abcd1234'
         - DOCKER_INFLUXDB_INIT_BUCKET=smartdata
         - DOCKER_INFLUXDB_INIT_ORG=smartgrow
         - DOCKER_INFLUXDB_INIT_RETENTION=1w
         - 'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=YKC-yCvdtWYnZTRPFv08CPWaJcozO4GQWrp-oFF0tikBJj-i7Tcu_n7sF1Gcxo4OaJzScdKJjm1RvNI56JeyOA=='

            
  

   grafana:
      user: root
      image: "grafana/grafana:8.5.3"
      ports:
         - "3000:3000"
      environment:
         - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
      volumes:
         - ./data/grafana:/var/lib/grafana
      secrets:
         - source: grafana_admin_password
           target: /run/secrets/admin_password
secrets:
   grafana_admin_password:
      file: ./data/secrets/grafana_admin_password
