version: "1.17.1"
services:

   emqx:
      user: root
      image: "emqx:latest"
      ports:
         - "18083:18083"
         - "1883:1883"
         - "4369:4369"
      volumes:
         - ./data/emqx/data:/opt/emqx/data
         - ./data/emqx/log:/opt/emqx/log
      environment:
         EMQX_LOADED_PLUGINS: emqx_auth_username emqx_auth_clientid
         EMQX_ADMIN_USERNAME: admin
         EMQX_ADMIN_PASSWORD: abcd1234
         
   influxdb:
      user: root
      image: "influxdb:latest"
      restart: unless-stopped
      ports:
         - "8086:8086"
      volumes:
         - ./data/influxdb/data:/var/lib/influxdb2
         - ./data/influxdb/config/:/etc/influxdb2
      environment:
         - DOCKER_INFLUXDB_INIT_MODE=setup
         - DOCKER_INFLUXDB_INIT_USERNAME=smartgrow
         - 'DOCKER_INFLUXDB_INIT_PASSWORD=abcd1234'
         - DOCKER_INFLUXDB_INIT_BUCKET=smartdata
         - DOCKER_INFLUXDB_INIT_ORG=smartgrow
         - DOCKER_INFLUXDB_INIT_RETENTION=1w
         - 'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ldU82bQr-ukNd_n8nCa-cJCbIAx6VV7Aii0hH3FywyoPP99GoHtArX02D11MrRD1aK3E0l2VnV5CneJ3_pE-Cg=='
   
   telegrafoutput:
      user: root
      image: "telegraf:latest"
      deploy:
         restart_policy:
            condition: on-failure
            delay: 30s
            max_attempts: 40
      volumes:
         - ./data/telegrafoutput/telegraf.conf:/etc/telegraf/telegraf.conf

   grafana:
      user: root
      image: "grafana/grafana:latest"
      ports:
         - "3000:3000"
      environment:
         - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
      volumes:
         - ./data/grafana:/var/lib/grafana
      secrets:
         - source: grafana_admin_password
           target: /run/secrets/admin_password
secrets:
   grafana_admin_password:
      file: ./data/secrets/grafana_admin_password
