version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - my-database
    command: npm run start:dev
  my-database:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE=smartgrow
      - MONGO_INITDB_ROOT_USERNAME=smartgrow
      - MONGO_INITDB_ROOT_PASSWORD=smartgrow1234
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
